"""Create appointment table and associations

Revision ID: d0930134cb37
Revises: 69ddd66e26b0
Create Date: 2024-05-07 16:22:43.351246

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0930134cb37"
down_revision: str | None = "69ddd66e26b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


status_enum = sa.Enum("SCHEDULED", "COMPLETED", "CANCELED", name="appointmentstatus")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            status_enum,
            nullable=False,
        ),
        sa.Column("total_duration", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("med_spa_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["med_spa_id"],
            ["med_spa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointment")
    status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
